# Dependencies
markdown:         redcarpet
highlighter:      rogue

# Permalinks
permalink:        pretty

# Setup
title:            Bitsmack
tagline:          'A web comic for people to read.'
description:      ''
url:              http://RC7502.github.io
baseurl:          /

author:
  name:           'RC'
  url:            https://twitter.com/bitsmack

paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
